# Generated by Django 4.2.4 on 2024-05-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=25)),
                ('codes', models.TextField()),
                ('discription', models.TextField()),
                ('types', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
