# Generated by Django 4.2.4 on 2024-05-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_codemodels_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codemodels',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='codemodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
