# Generated by Django 4.2.11 on 2024-06-21 15:41

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_rename_discription_codemodels_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='codemodels',
            name='language',
        ),
        migrations.RemoveField(
            model_name='codemodels',
            name='types',
        ),
        migrations.AddField(
            model_name='codemodels',
            name='code_lang',
            field=models.ForeignKey(default=builtins.print, on_delete=django.db.models.deletion.CASCADE, to='dataapp.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codemodels',
            name='type_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dataapp.types'),
            preserve_default=False,
        ),
    ]
